# Generated by Django 4.1.7 on 2023-03-22 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('birthday', models.DateField()),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widow', 'Widow'), ('widower', 'Widower')], max_length=15)),
                ('religion', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('occupation', models.CharField(max_length=50)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address', serialize=False, to='api.patient')),
                ('building_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('street', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('village', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('barangay', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dentition',
            fields=[
                ('patient_id', models.OneToOneField(choices=[('class(molar)', 'CLASS(MOLAR)'), ('overjet', 'OVERJET'), ('overbite', 'OVERBITE'), ('midline deviation crossbite', 'MIDLINE DEVIATION CROSSBITE')], on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_dentition', serialize=False, to='api.patient')),
                ('periodontal_screening', models.CharField(max_length=25)),
                ('occlusion', models.CharField(max_length=25)),
                ('appliances', models.CharField(max_length=25)),
                ('tmd', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_full_info', serialize=False, to='api.patient')),
                ('goodhealth', models.BooleanField(default=False)),
                ('current_treatment', models.CharField(blank=True, max_length=255, null=True)),
                ('isIllnessOrOperation', models.CharField(choices=[('illness', 'Illness'), ('operation', 'Operation'), ('n/a', 'N/A')], default='n/a', max_length=255)),
                ('hospitalization', models.BooleanField(default=False)),
                ('medication', models.CharField(blank=True, max_length=255, null=True)),
                ('tobacco', models.BooleanField(default=False)),
                ('isAlchoholOrDrugs', models.CharField(choices=[('alchohol', 'Alchohol'), ('drugs', 'Drugs'), ('n/a', 'N/A')], default='n/a', max_length=255)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('bloodtype', models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMinor',
            fields=[
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_minor_info', serialize=False, to='api.patient')),
                ('guardian_name', models.CharField(max_length=150)),
                ('occupation_guardian', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientWoman',
            fields=[
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_woman_info', serialize=False, to='api.patient')),
                ('pregnancy', models.BooleanField(default=False)),
                ('nursing', models.BooleanField(default=False)),
                ('birth_control', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tooth_no', models.PositiveBigIntegerField()),
                ('procedure', models.CharField(max_length=255)),
                ('amount_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_treatments', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ToothStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_no', models.PositiveBigIntegerField()),
                ('conditions', models.CharField(blank=True, choices=[('D', 'Decayed'), ('M', 'Missing'), ('F', 'Filled'), ('I', 'Caries Indicated for Extraction'), ('RF', 'Root Fragment'), ('MO', 'Missing due to Other Cause'), ('Im', 'Impacted Tooth'), ('J', 'Jacket Crown'), ('A', 'Amalgam Filling'), ('AB', 'Abutment'), ('P', 'Pontic'), ('In', 'Inlay'), ('Fx', 'Fixed Cure Composite'), ('S', 'Sealants'), ('Rm', 'Removable Denture'), ('X', 'Extraction due to Caries'), ('XO', 'Extraction due to Other Cause'), ('Cm', 'Cingenitally Missing'), ('Sp', 'Supernumerary')], default='', max_length=50, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tooth_status', to='api.dentition')),
            ],
        ),
    ]
