# Generated by Django 4.1.7 on 2023-03-29 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_patientinformation_isalchoholordrugs_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientinformation",
            old_name="isAlchoholOrDrugs",
            new_name="isAlcoholOrDrugs",
        ),
    ]
