# Generated by Django 4.1.7 on 2023-03-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_isalchoholordrugs_patientinformation_isalcoholordrugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinformation",
            name="isAlcoholOrDrugs",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
