# Generated by Django 4.2 on 2023-04-11 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dentition_appliances_alter_dentition_occlusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientwoman',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_woman_info', serialize=False, to='api.patientinformation'),
        ),
    ]
