# Generated by Django 4.2 on 2023-04-11 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_patientinformation_patientmedicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medical_history', serialize=False, to='api.patient')),
                ('goodhealth', models.BooleanField(default=False)),
                ('current_treatment', models.CharField(blank=True, max_length=255, null=True)),
                ('isIllnessOrOperation', models.CharField(blank=True, max_length=255, null=True)),
                ('hospitalization', models.BooleanField(default=False)),
                ('medication', models.CharField(blank=True, max_length=255, null=True)),
                ('tobacco', models.BooleanField(default=False)),
                ('isAlcoholOrDrugs', models.BooleanField(default=False, null=True)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('bloodtype', models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patientwoman',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='woman_info', serialize=False, to='api.medicalhistory'),
        ),
        migrations.DeleteModel(
            name='PatientMedicalHistory',
        ),
    ]
