# Generated by Django 4.2 on 2023-04-29 09:41

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_medicalhistory_alter_patientwoman_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentition',
            name='appliances',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('orthodontic', 'ORTHODONTIC'), ('stayplate', 'STAYPLATE'), ('', '')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dentition',
            name='occlusion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('class(molar)', 'CLASS(MOLAR)'), ('overjet', 'OVERJET'), ('overbite', 'OVERBITE'), ('midline deviation crossbite', 'MIDLINE DEVIATION CROSSBITE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dentition',
            name='periodontal_screening',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('gingivitis', 'GINGIVITIS'), ('early periodontitis', 'EARLY PERIODONTITIS'), ('moderate periodontitis', 'MODERATE PERIODONTITIS'), ('advanced periodontitis', 'ADVANCED PERIODONTITIS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dentition',
            name='tmd',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('clenching', 'CLENCHING'), ('clicking', 'CLICKING'), ('trismus', 'TRISMUS'), ('muscle spasm ', 'MUSCLE SPASM')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='toothstatus',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth_status', to='api.dentition'),
        ),
        migrations.RemoveField(
            model_name='treatmentrecord',
            name='procedure',
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='procedure',
            field=models.ManyToManyField(related_name='treatment_procedures', to='api.procedure'),
        ),
    ]
